name: lvminit
version: 0.0.1
description: Kubernetes LVM init app
appVersion: 0.0.1
apiVersion: v1
keywords:
  - storage
  - block-storage
  - volume
  - lvm
sources:
  - https://github.com/dtrdnk/lvminit
